### ISSUE TITLE
Support for buttercup

### ISSUE THREAD

**Issue by DamienCassou** [doublep/eldev#1]
Hi,

I'm the author of [makel](https://gitea.petton.fr/DamienCassou/makel), a Makefile which helps me check my Emacs projects. I'm very much interested into your project but can't switch to it just yet because it misses a few things I really care about: checking the quality of code and running buttercup tests. Do you think it would make sense to add both to eldev?

By the way, I added eldev as an alternative to makel: https://gitea.petton.fr/DamienCassou/makel/src/branch/master/README.org#alternatives

**Comment by doublep** [comment]
I plan to add support for all popular testing frameworks, and Buttercup looks like one of those. Tentatively scheduling for 0.2 because of this issue.

About linting I'm not so sure. I'm generally not a fan myself (it tends to give warnings on my code that I don't agree with or don't think they are worth fixing). There appear to be many different linters — though, on the other hand, there are many testing frameworks as well. It would be good if you described in more details what exactly you expect: difficult to design something you don't need yourself. But please create another issue: leave this one for Buttercup and add one more for linting (or vice versa).

Also, not everything has to be implemented in Eldev directly. You can add more code (even new commands, for example) in your project's `Eldev` file. Though I understand that you wouldn't want to add similar code in ten different projects.

**Comment by DamienCassou** [comment]
> please create another issue: leave this one for Buttercup and add one more for linting

ok, I've created issues #2, #3 and #4.

> I'm generally not a fan myself (it tends to give warnings on my code that I don't agree with or don't think they are worth fixing)

Checkdoc got better at that recently, reporting less useless problems. I think all warnings I get nowadays are worth fixing. Even if I get a warning I don't think is really problematic, I will fix it anyway to have 0 warnings on my code: this helps me make sure I don't miss any important warning.

**Comment by doublep** [comment]
Committed support for Buttercup. Certain features implemented for ERT are not supported currently (maybe with future Buttercup improvements, we'll see). Can you test this a bit? No need to declare anything, it should just autodetect the framework your project uses. If it doesn't for whatever reason, you can add `(setf eldev-test-framework 'buttercup)` to file `Eldev`.

**Comment by doublep** [comment]
Done in 0.2.
