### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by sirikid** [doublep/eldev#15]
I hope this picture is enough 
![image](https://user-images.githubusercontent.com/4840430/86372292-a6502380-bc8a-11ea-817b-3270749bb9bb.png)

**Comment by doublep** [comment]
No, I don't know what `[1]` means. Locally it fails two times in the same way.

If you are missing the fix for #14, then it is because it is not released yet. See also https://github.com/doublep/eldev#upgrading-eldev.

**Comment by sirikid** [comment]
If there are no files with package headers why is the second invocation succeed? Should it?

**Comment by doublep** [comment]
Ah, I didn't notice that the second time the answer was `n`. It succeeds because if Eldev doesn't have to guess archive, it never create package descriptor as not needed, so certain function in Emacs package module doesn't fail.

But actually, I think the first invocation also shouldn't fail. Maybe it should print a warning, but otherwise succeed (without guessing the archive of course, as that would be impossible). I.e. it should be possible to run `eldev init` even in an empty directory, though of course later you'd have to tweak file `Eldev` manually. What do you think?

**Comment by sirikid** [comment]
I think consistent and predictable behaviour is a top priority for development tools. So either both calls must succeed or both must fail.

It might be worth adding the `new`/`create` command to create a project from the template.

**Comment by doublep** [comment]
> I think consistent and predictable behaviour is a top priority for development tools. So either both calls must succeed or both must fail.

Now both succeed. However, default mode of `init` command is interactive: it will ask you if you really want to continue even if the current directory doesn't seem to contain a project (if you plan to create a project, just answer `y`). There is also option `-n` (`--non-interactive`). In this mode the command never asks anything and should always succeed, unless file `Eldev` is already there. However, in this mode archive autoguessing won't be performed.

> It might be worth adding the new/create command to create a project from the template.

I feel a template would be largely empty here. Maybe it could create the main `.el` file with lots of placeholders (author, license, etc.), but there's not much else boilerplate common to all projects.

**Comment by sirikid** [comment]
I thought about flycheck and company, but even they've not so many common parts.
