### ISSUE TITLE
unable to run code with a different version

### ISSUE THREAD

**Issue by Trevoke** [doublep/eldev#51]
Hi! I am using eldev 0.9.2 . 

According to the [documentation](https://github.com/doublep/eldev#different-emacs-versions) I should be able to do this: 

`% EMACS=emacs27.2 eldev test`

But i get this error:

> /home/stag/bin/eldev: 35: emacs27.2: not found

This also goes wrong if I try `EMACS=emacs25` which is the example. Am I doing something wrong?

**Comment by doublep** [comment]
Well, is it installed? Is it in `$PATH`? This is the same error I get if I do e.g. `$ EMACS=emacs999 eldev test`:

> /home/paul/.local/bin/eldev: 35: emacs999: not found

Basically, Eldev cannot do magic, you have to have Emacs of that version installed. It can be named whatever, it's just a name, e.g. `EMACS=emacs-with-funny-extensions ...` will work fine as long as that executable exists in `$PATH` and is some supported Emacs version. Eldev only guarantees that you can run using different versions interchangeably and this will not screw some internal state (the only exception, AFAIR, are byte-compiled files if you use those, but this is a general Emacs limitation).

**Comment by Trevoke** [comment]
Okay, makes sense. I assumed that since eldev handles package retrieval and installation, it might also handle installing and keeping track of versions of emacs.

Since it doesn't, I guess I have some additional work to do. Thanks.

What are the odds we can add a feature for eldev to retrieve/install multiple emacs versions? It might be able to piggyback on top of [evm](https://github.com/rejeep/evm) ?

**Comment by doublep** [comment]
> What are the odds we can add a feature for eldev to retrieve/install multiple emacs versions?

Doesn't sound likely, because this seems to be very difficult to do across various supported OSes. If you want you can try creating a PR, I'd be willing to accept e.g. "this doesn't work on Windows", but even then I'd estimate this to be extremely complicated.

> It might be able to piggyback on top of evm ?

Maybe, I never tried. Personally, I have installed a few versions of Emacs from Git and manually renamed `/usr/local/bin/emacs` to `emacs-VERSION`. This worked fine for me, though I never managed to compile anything older than 25.2.

> I assumed that since eldev handles package retrieval and installation, it might also handle installing and keeping track of versions of emacs.

Fair enough, never looked at it from this angle. I will add a couple of sentences to the documentation to clear possible confusion.

**Comment by doublep** [comment]
Thank you. I cannot solve this, but at least I improved documentation to avoid further confusion.

**Comment by doublep** [comment]
By the way, there is now `eldev docker` command that might be what you need.

**Comment by Trevoke** [comment]
Oh that is awesome, thank you !
