### ISSUE TITLE
Automatically detect ELDEV_LOCAL

### ISSUE THREAD

**Issue by declanqian** [doublep/eldev#63]
Automatically set `ELDEV_LOCAL` when runing `eldev` directly from source.

I have a copy of `eldev` source using `straight.el`.
IMO, It's kind of chore to set envs like `ELDEV_LOCAL`.

Does changes like [this](https://github.com/declanqian/eldev/commit/2f9473d20e084c6bb20a13e17dd4d51d2b353865)) make sense?

**Comment by doublep** [comment]
This seems to be too confusing. I don't really want automatism here. I have `export ELDEV_LOCAL="~/eldev"` in my `~/.profile`, which is enough for most purposes. But I also sometimes run `ELDEV_LOCAL= eldev ...` to quickly see differences in behavior between local code I change and the stable package.

**Comment by declanqian** [comment]
> I have `export ELDEV_LOCAL="~/eldev"` in my `~/.profile`, which is enough for most purposes

Well this doesn't seem ideal to me. More like a hard-code setting, in my case I guess it would
be `~/.config/emacs/var/straight/repos/eldev`. I don't want this random path in my profile, mainly because I only want to try it out at this point.

The use case here I think (developer experience(installation process) point of view):

- Random user download a `eldev-0.10.3.zip` (or git clone source) from GitHub
- Don't want to use the `install.sh` script yet, cause it makes me think what changes it will make to my system.
- Try it out by using `~/.config/emacs/var/straight/repos/eldev` or `~/Downloads/eldev-0.10.3/bin/eldev`.
It worked by downloading(or coping) a stable copy into directory `~/.eldev/28.0/bootstrap/eldev-0.10.3/` . To me, they seem to be redundant files, which also includes a bin directory...
- Later Emacs users most likely will make some changes to the el files in `~/Downloads/eldev-0.10.3` which will make no difference

Anyway, not a deep user here. But I do have some other questions:

- Will it showup in [system package manager](https://aur.archlinux.org/packages/cask/)?
- Does it make sense to use [straight.el](https://github.com/raxod502/straight.el#features) instead of `package.el`?
see the [comparison](https://github.com/raxod502/straight.el#comparison-to-packageel).
Also, it has a feature called lockfiles.

**Comment by doublep** [comment]
> I don't want this random path in my profile, mainly because I only want to try it out at this point.

Then just run `export ELDEV_LOCAL="~/eldev"` in a console. Until you close it, the variable will be set there. From my point of view, `ELDEV_LOCAL` is a developer-only thing and should never be implicitly set. If you want it, you need to make an explicit decision.

> Will it showup in system package manager?

If someone asks and someone takes effort to add and maintain a package. Such a package would consist basically of just the short script, because bootstrapping happens automatically. I won't make any efforts to arrange this myself in any distro, though.

> Does it make sense to use straight.el instead of package.el?

No. Eldev is supposed to provide a "native Emacs" environment. Maybe using `straight.el` could become an *option*, but certainly not by default, i.e. not *instead* of native Emacs code.

**Comment by declanqian** [comment]
Thank you for taking my questions. Closing this one.
